ror_api/ror_api_personal_site/config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :topics

    end
  end
end

ror_api/ror_api_personal_site/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ror_api/ror_api_personal_site/app/models/topic.rb
class Topic < ApplicationRecord
end

ror_api/ror_api_personal_site/app/controllers/api/v1/topics_controller.rb
class Api::V1::TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
    render json: @topics
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    render json: @topic
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # # POST /topics
  # # POST /topics.json
  # def create
  #   @topic = Topic.new(topic_params)

  #   respond_to do |format|
  #     if @topic.save
  #       format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
  #       format.json { render :show, status: :created, location: @topic }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @topic.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /topics/1
  # # PATCH/PUT /topics/1.json
  # def update
  #   respond_to do |format|
  #     if @topic.update(topic_params)
  #       format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @topic }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @topic.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /topics/1
  # DELETE /topics/1.json
  # def destroy
  #   @topic.destroy
  #   respond_to do |format|
  #     format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:name, :description, :importantance)
    end
end

ror_api/ror_api_personal_site/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

ror_api/ror_api_personal_site/app/helpers/application_helper.rb
module ApplicationHelper
end

ror_api/ror_api_personal_site/app/helpers/topics_helper.rb
module TopicsHelper
end

ror_api/ror_api_personal_site/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorApiPersonalSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

ror_api/ror_api_personal_site/app/views/topics/_form.html.erb
<%= form_with(model: topic, local: true) do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :topic_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :topic_description %>
  </div>

  <div class="field">
    <%= form.label :importantance %>
    <%= form.number_field :importantance, id: :topic_importantance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ror_api/ror_api_personal_site/app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

ror_api/ror_api_personal_site/app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Importantance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.name %></td>
        <td><%= topic.description %></td>
        <td><%= topic.importantance %></td>
        <td><%= link_to 'Show', topic %></td>
        <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

ror_api/ror_api_personal_site/app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path %>

ror_api/ror_api_personal_site/app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @topic.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @topic.description %>
</p>

<p>
  <strong>Importantance:</strong>
  <%= @topic.importantance %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>